---
- name: Uninstall Amazon Corretto JDK 17 from all VMs
  hosts: all
  become: yes
  tasks:
    - name: Remove Amazon Corretto JDK 17
      apt:
        name: java-17-amazon-corretto-jdk
        state: absent

    - name: Remove Amazon Corretto APT repository
      file:
        path: /etc/apt/sources.list.d/amazon-corretto.list
        state: absent

    - name: Remove the GPG key for Amazon Corretto
      file:
        path: /etc/apt/keyrings/amazon-corretto.asc
        state: absent

    - name: Clean up apt cache
      apt:
        autoclean: yes
        autoremove: yes
