version: "3.9"

services:
  java_app:
    container_name: java_app
    image: spring_boot_crud
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/spring_crud
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: spring_crud
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: { }