apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  namespace: firstns
  labels:
    app: myapp
    release: stable
    team: red

spec:
  containers:
    - name: redis-container
      image: redis:latest
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 80
